= OpenRC runscript for QEMU

This is (opinionated) OpenRC runscript for QEMU virtual machines.

____ 
You don’t need https://libvirt.org[libvirt] and its https://libvirt.org/formatdomain.html[awful XML configs] to use QEMU/KVM!
Forked from https://github.com/jirutka/qemu-openrc 
____

==Added features: 
* Support passthrough usb, PCI devices.
* Support SATA devices and OVMF for UEFI


== Requirements (only need when you intend to use VIRTIO.）

* https://wiki.gentoo.org/wiki/OpenRC[OpenRC]
* Bash or Busybox’s ash (should work also with other POSIX shells)
* http://www.dest-unreach.org/socat[socat]
* Linux kernel with virtio drivers
+
    CONFIG_HW_RANDOM_VIRTIO=y
    CONFIG_SCSI_VIRTIO=y
    CONFIG_VIRTIO=y
    CONFIG_VIRTIO_BALLOON=y
    CONFIG_VIRTIO_NET=y
    CONFIG_VIRTIO_PCI=y


== Installation

=== Alpine Linux

Install package https://pkgs.alpinelinux.org/package/v3.4/main/x86_64/qemu-openrc[qemu-openrc]:

    apk add qemu-openrc


=== Manually

. Install socat:
+
[source, sh]
----
emerge -av net-misc/socat sys-firmware/edk2-ovmf # on Gentoo 
apk add socat ovmf  # on Alpine
----

. Clone this repository and jump in:
+
    git clone https://github.com/jirutka/qemu-openrc.git
    cd qemu-openrc

. Install runscript, example config and qemush utility:
+
    ./install
+
You may use variables `DESTDIR` and `PREFIX` to specify the target directories.


== How to configure a new VM

. Symlink runscript `qemu` for your new VM named `alpine`:
+
    cd /etc/init.d
    ln -s qemu qemu.alpine

. Configure your new VM:
+
    cd /etc/conf.d
    cp qemu qemu.alpine
    vim qemu.alpine

. Start your new VM:
+
    rc-service qemu.alpine start


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
